services:
  - type: web
    name: requirement-doc-helper
    env: node
    plan: free
    region: singapore
    buildCommand: |
      npm install
      cd client && npm install && npm run build
    startCommand: npm run server
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: OPENAI_API_KEY
        sync: false
      - key: OPENAI_BASE_URL
        value: https://api.openai.com/v1
      - key: PORT
        value: 3001
